package com.frcteam3636.frc2026.subsystems.drivetrain

import com.frcteam3636.frc2026.utils.autos.flipPath
import com.frcteam3636.frc2026.utils.math.meters
import com.frcteam3636.frc2026.utils.math.radians
import com.therekrab.autopilot.APTarget
import edu.wpi.first.math.geometry.Pose2d
import edu.wpi.first.math.geometry.Rotation2d
import edu.wpi.first.wpilibj2.command.Command
import edu.wpi.first.wpilibj2.command.Commands

interface Auto {
    fun getPath(drivetrain: Drivetrain, flipH: Boolean, flipV: Boolean): Command
}

object TestAuto: Auto {

    // Generated by autopilot path picker
    enum class Targets(val target: APTarget) {
        Target1(
            APTarget(
                Pose2d(
                    2.3.meters,
                    2.9.meters,
                    Rotation2d(1.579.radians.unaryMinus())
                )
            ).withEntryAngle(Rotation2d(0.radians))
        ),
        Target2(
            APTarget(
                Pose2d(
                    2.3.meters,
                    0.8.meters,
                    Rotation2d(1.57.radians))
            )
        )
    }

    override fun getPath(drivetrain: Drivetrain, flipH: Boolean, flipV: Boolean): Command = Commands.sequence(
        drivetrain.alignSideRelative(Targets.Target1.target, flipH, flipV),
        drivetrain.alignSideRelative(Targets.Target2.target, flipH, flipV)
    )

//    override fun getPath(drivetrain: Drivetrain, flipH: Boolean, flipV: Boolean): Command =
//        testAutoPath (
//            flipPath(arrayOf(Targets.entries..target), flipH, flipV)
//        )
}
